name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - uses: UmbrellaDocs/action-linkspector@v1
  find-uvis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # Required for commenting on PRs
    steps:
      - uses: narthur/uvi-finder@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}