name: Merge
on:
  push:
    branches:
      - master
jobs:
  find-uvis:
    runs-on: ubuntu-latest
    steps:
      - uses: narthur/uvi-finder@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
  bm:
    needs: find-uvis
    runs-on: ubuntu-latest
    steps:
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@v1.1.0
        with:
          USERNAME: tskrtcht
          AUTH_TOKEN: ${{ secrets.BEEMINDER_TSKRTCHT_AUTH_TOKEN }}
          GOAL: uvi
          VALUE: ${{ needs.find-uvis.outputs.uvi-count }}